### ISSUE TITLE
Label for missing code formatting

### ISSUE THREAD

**Issue by schmunk42** [yiisoft-contrib/github-bot#12]
Add label, which makes the bot telling the user in a nice way, that he should format his issue in a proper way.

Example: https://github.com/yiisoft/yii2/issues/15160

**Comment by samdark** [comment]
Good idea.

**Comment by samdark** [comment]
Thank you for your issue. Unfortunately code that is not formatted as code blocks is extremely hard to read. Please check [GitHub formatting guide](https://guides.github.com/features/mastering-markdown/) and wrap code accordingly. Thank you.

**Comment by samdark** [comment]
Is it good?

**Comment by schmunk42** [comment]
LGTM
