### ISSUE TITLE
Add solved label

### ISSUE THREAD

**Issue by schmunk42** [yiisoft-contrib/github-bot#15]
It would be nice if the bot could understand a label "solved".

It should close the issue and add a text like: "To our understanding this issue is solved, please comment or reopen, if you still experiencing problems with this topic".

It would also help when browing issues on GitHub.

**Comment by cebe** [comment]
isn't solved = closed, not solved = open?

**Comment by samdark** [comment]
Yes. It's just closing the issue. No need for separate label.

**Comment by samdark** [comment]
See how it works? ;)

**Comment by schmunk42** [comment]
I think there's a difference between solved and closed.

**Solved** can be "fixed", "question answered", "configuration example attached", etc...
While **closed** is also "won't fix", "does not apply", ...

Personally, I sometimes hesitate to close issues in my projects, despite the fact **I** think it is solved, but I want to wait for feedback of the user. But very often you do not get that feedback. And just closing without any explanation is also not ideal.

**Comment by samdark** [comment]
Don't hesitate and close issues you think are solved right away. It makes no sense for these to hang around.

**Comment by cebe** [comment]
If it is not fixed but relevant it will be reported again.
