### ISSUE TITLE
Bot writes answer for 'question' label twice.

### ISSUE THREAD

**Issue by dmirogin** [yiisoft-contrib/github-bot#16]
Example:
https://github.com/yiisoft/yii2-elasticsearch/issues/186#issuecomment-396701834

**Comment by samdark** [comment]
@cebe any idea why?

**Comment by cebe** [comment]
log says:

```
2018-06-13 09:54:51 [192.30.252.37][-][-][info][action] commented on issue yiisoft/yii2-elasticsearch#186.
2018-06-13 09:54:53 [192.30.252.37][-][-][info][action] closed issue yiisoft/yii2-elasticsearch#186.
```

so it logged the action only once... no idea why this happened

**Comment by dmirogin** [comment]
Am i broken ? 😆 
https://github.com/yiisoft/yii2-authclient/pull/232

**Comment by samdark** [comment]
Deleted another one... It happens so either logging is done bad or GitHub API has a bug.

**Comment by cebe** [comment]
unable to reproduce here... https://github.com/cebe/testrepo/issues/4

**Comment by cebe** [comment]
same here, works as expected: https://github.com/cebe/testrepo/issues/5

**Comment by cebe** [comment]
I found the problem:

![bildschirmfoto von 2018-07-04 13-34-05](https://user-images.githubusercontent.com/189796/42274990-fc49cfce-7f8e-11e8-8b57-9e33c941a552.png)

we have duplicate entry on the webhooks in some repos :)
going to fix that soon.
