### ISSUE TITLE
Pull request events do not work

### ISSUE THREAD

**Issue by cebe** [yiisoft-contrib/github-bot#6]
currently the bot registers for `issues` events. For labels on pull requests to work, we need to register for `pull_request` events too. https://developer.github.com/v3/activity/events/types/#pullrequestevent

**Comment by samdark** [comment]
"Moving" labels should be disabled for pull requests.

**Comment by cebe** [comment]
steps to do:
- register for `pull_request` events here: https://github.com/yiisoft-contrib/github-bot/blob/5194029562cb3d4ace281639e5ef8dd8626c2385/commands/GithubController.php#L76
- allow `pull_request` events here: https://github.com/yiisoft-contrib/github-bot/blob/5194029562cb3d4ace281639e5ef8dd8626c2385/controllers/IssuesController.php#L49
- then adjust this method to work on PR data also:
  https://github.com/yiisoft-contrib/github-bot/blob/5194029562cb3d4ace281639e5ef8dd8626c2385/controllers/IssuesController.php#L78
  moving PRs should not be allowed.
